/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_keplerproject_luajava_fast_FjluaDll */

#ifndef _Included_org_keplerproject_luajava_fast_FjluaDll
#define _Included_org_keplerproject_luajava_fast_FjluaDll
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_open
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1open
  (JNIEnv *, jclass);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_newthread
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1newthread
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_getTop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1getTop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_setTop
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1setTop
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_pushValue
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1pushValue
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_remove
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1remove
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_insert
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1insert
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_replace
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1replace
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_checkStack
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1checkStack
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_xmove
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1xmove
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_isNumber
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1isNumber
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_isString
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1isString
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_isCFunction
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1isCFunction
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_isUserdata
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1isUserdata
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_type
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1type
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_typeName
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1typeName
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_equal
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1equal
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_rawequal
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1rawequal
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_lessthan
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1lessthan
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_toNumber
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1toNumber
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_toInteger
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1toInteger
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_toBoolean
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1toBoolean
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_toString
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1toString
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_objlen
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1objlen
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_toThread
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1toThread
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_pushNil
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1pushNil
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_pushNumber
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1pushNumber
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_pushInteger
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1pushInteger
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_pushString
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1pushString__JLjava_lang_String_2
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_pushString
 * Signature: (J[BI)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1pushString__J_3BI
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_pushBoolean
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1pushBoolean
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_getTable
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1getTable
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_getField
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1getField
  (JNIEnv *, jclass, jlong, jint, jstring);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_rawGet
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1rawGet
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_rawGetI
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1rawGetI
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_createTable
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1createTable
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_getMetaTable
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1getMetaTable
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_getFEnv
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1getFEnv
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_setTable
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1setTable
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_setField
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1setField
  (JNIEnv *, jclass, jlong, jint, jstring);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_rawSet
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1rawSet
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_rawSetI
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1rawSetI
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_setMetaTable
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1setMetaTable
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_setFEnv
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1setFEnv
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_call
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1call
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_pcall
 * Signature: (JIII)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1pcall
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_yield
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1yield
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_resume
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1resume
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_status
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1status
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_gc
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1gc
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_error
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1error
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_next
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1next
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_concat
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1concat
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_pop
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1pop
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_newTable
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1newTable
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_strlen
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1strlen
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_isFunction
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1isFunction
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_isTable
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1isTable
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_isNil
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1isNil
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_isBoolean
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1isBoolean
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_isThread
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1isThread
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_isNone
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1isNone
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_isNoneOrNil
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1isNoneOrNil
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_setGlobal
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1setGlobal
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_getGlobal
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1getGlobal
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_getGcCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1getGcCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_LdoFile
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1LdoFile
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_LdoString
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1LdoString
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_LgetMetaField
 * Signature: (JILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1LgetMetaField
  (JNIEnv *, jclass, jlong, jint, jstring);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_LcallMeta
 * Signature: (JILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1LcallMeta
  (JNIEnv *, jclass, jlong, jint, jstring);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_Ltyperror
 * Signature: (JILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1Ltyperror
  (JNIEnv *, jclass, jlong, jint, jstring);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_LargError
 * Signature: (JILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1LargError
  (JNIEnv *, jclass, jlong, jint, jstring);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_LcheckString
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1LcheckString
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_LoptString
 * Signature: (JILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1LoptString
  (JNIEnv *, jclass, jlong, jint, jstring);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_LcheckNumber
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1LcheckNumber
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_LoptNumber
 * Signature: (JID)D
 */
JNIEXPORT jdouble JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1LoptNumber
  (JNIEnv *, jclass, jlong, jint, jdouble);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_LcheckInteger
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1LcheckInteger
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_LoptInteger
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1LoptInteger
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_LcheckStack
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1LcheckStack
  (JNIEnv *, jclass, jlong, jint, jstring);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_LcheckType
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1LcheckType
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_LcheckAny
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1LcheckAny
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_LnewMetatable
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1LnewMetatable
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_LgetMetatable
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1LgetMetatable
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_Lwhere
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1Lwhere
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_Lref
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1Lref
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_LunRef
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1LunRef
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_LgetN
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1LgetN
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_LsetN
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1LsetN
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_LloadFile
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1LloadFile
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_LloadBuffer
 * Signature: (J[BJLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1LloadBuffer
  (JNIEnv *, jclass, jlong, jbyteArray, jlong, jstring);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_LloadString
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1LloadString
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_Lgsub
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1Lgsub
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_LfindTable
 * Signature: (JILjava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1LfindTable
  (JNIEnv *, jclass, jlong, jint, jstring, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_openBase
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1openBase
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_openTable
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1openTable
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_openIo
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1openIo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_openOs
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1openOs
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_openString
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1openString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_openMath
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1openMath
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_openDebug
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1openDebug
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_openPackage
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1openPackage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_openLibs
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1openLibs
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    fjlua_open
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_fjlua_1open
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    fjlua_beginModule
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_fjlua_1beginModule
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    fjlua_beginClass
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_fjlua_1beginClass
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    fjlua_regFunc
 * Signature: (JLjava/lang/String;IZ)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_fjlua_1regFunc
  (JNIEnv *, jclass, jlong, jstring, jint, jboolean);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    fjlua_endClass
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_fjlua_1endClass
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    fjlua_endModule
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_fjlua_1endModule
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    fjlua_pushJavaObj
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_fjlua_1pushJavaObj
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_getObjectFromUserdata
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1getObjectFromUserdata
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_keplerproject_luajava_fast_FjluaDll
 * Method:    lua_isJavaObject
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_keplerproject_luajava_fast_FjluaDll_lua_1isJavaObject
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
